default: &default

development:
  <<: *default
  database: sample_app_development
  adapter: sqlite3
  database: db/db_dev_db.sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: sample_app_test
  adapter: sqlite3
  database: db/db_dev_db.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: sample_app_production
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>